# -*- coding: utf-8 -*-
"""memo_list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j0JUs1ek9It5JygP5x6GogckUX2bsxSM
"""

memo_list = [100, 200, 100, 400, 500, 300, 600] #"I want to run a few Python list operations on memo_list."

memo_list.count(100)  #"Count how many times the number 100 appears."

memo_list.count(500)

memo_list.append(700) #"I want to append the number 700 to memo_list."

memo_list  #"After I load a command, I want to call memo_list again to see if the command was executed correctly."  #yes:)

memo_list.reverse() #"I want to reverse the arrays inside the parentheses with this command."

memo_list  #"I want to reverse the arrays inside the parentheses with this command."

memo_list.sort()  #"I want to sort my arrays or data, so I will use this command."

memo_list   #"Now we will get an output."

memo_list.pop(2) #"I can use the pop() method to remove an element from a list in two ways.
 #If I put a value like 2 inside the parentheses, it means to remove the number 2 from the list. If I don't put a value inside the parentheses in the pop() method, it automatically removes the last element. And if I take the output, that is, if I read the arrays again, the last number or the number specified inside the parentheses is deleted."

memo_list[4] #"This method is for accessing the members inside the list."

memo_list[-1]

memo_list[-4:-1] #"This command means to read the members from this value to that value."

memo_list[-1:-4] #In the second command, you use slice notation to read the elements of the list from index -1 to index -4. Index -4 means the element before the last element of the list. Therefore, the second command reads no elements, because the element before the last element of the list does not exist.

memo_list[0]

memo_list.remove(400) #"remove the number 400 from my list."

memo_list #"Now we will get an output."

memo_list.copy()

memo_list.index(100)  #In the Python programming language, the index() method is used to find the index of an element in a list. The method takes a value as an argument and returns the index of the first occurrence of that value in the list.

memo_list.index(500)

memo_list.clear()

memo_list   ##"Now we will get an output."